Disabling the row mode widget
hidronautics/PoolsideGUI pull request #34
Opened 2021-09-14 18:01 UTC by starykhGrigogii

2021-09-15 18:01 UTC, vladushked commented on mainwindow.cpp
> +    foreach (QProgressBar *bar, thrusterBarGroup) {
foreach желательно заменить на обычный for

2021-09-15 18:01 UTC, vladushked commented on mainwindow.cpp
> +    connect(serial_client, SIGNAL(dataUpdated()), this, SLOT(updateDataUi()));
можно назвать просто updateUi()

2021-09-15 18:01 UTC, vladushked commented on mainwindow.cpp
>  void MainWindow::reconnectROV() // TODO: присутствует утечка пямяти при reconnectROV из-заnew Serial_Client
я заметил в конструкторе emit reconnectROV();
это зачем
это же не сигнал

2021-09-15 18:01 UTC, vladushked commented on mainwindow.cpp
>      Serial_Client *serial_client = new Serial_Client();
стоп
у тебя же есть уже serial_client переменная в mainwindow

2021-09-15 18:01 UTC, vladushked commented on mainwindow.cpp
>      udp_client = new UDP_Client();
дублирование кода
все это есть в reconnectROV

2021-09-15 18:01 UTC, vladushked commented on mainwindow.cpp
> +    UDP_Client *udp_client = new UDP_Client();
опять же
здесь желательно удалять старый экземпляр

delete udp_client;

а уже потом выделять память под новый

то же самое и с serial_client

2021-09-15 18:01 UTC, vladushked commented on mainwindow.cpp
>  void MainWindow::reconnectROV() // TODO: присутствует утечка пямяти при reconnectROV из-заnew Serial_Client
слово emit там не нужо

2021-09-15 18:01 UTC, vladushked commented on mainwindow.cpp
> +    foreach (QProgressBar *bar, thrusterBarGroup) {
вообще везде
это старая тема как я понял
сейчас есть range based for

2021-09-15 18:01 UTC, vladushked commented on mainwindow.cpp
>      controller = new Mouse3d("3dMouse", 5);
под контроллеры стоит сделать отдельный управляющий класс чтобы не было путаницы
это в трелло я добавил

2021-09-15 18:01 UTC, vladushked commented on mainwindow.cpp
>      controller = new Mouse3d("3dMouse", 5);
или если он уже есть то создавать контроллеры в нем

2021-09-15 18:41 UTC, starykhGrigogii commented on mainwindow.cpp
>      controller = new Mouse3d("3dMouse", 5);
оно будет переделываться, когда я буду переделывать настройку девайсов

2021-09-15 20:28 UTC, Marseloz commented on mainwindow.cpp
>  void MainWindow::reconnectROV() // TODO: присутствует утечка пямяти при reconnectROV из-заnew Serial_Client
это пока куски из старого кода, в процессе я их удалю

2021-09-16 16:48 UTC, vladushked requested changes

2021-09-16 16:48 UTC, vladushked commented on mainwindow.cpp
> +    for(qsizetype i = 0; i < settings->childKeys().size(); i++) {
Здесь я имел ввиду range based for
То есть
for( auto *key : settings->childKeys()) {}

2021-09-16 16:48 UTC, vladushked commented on mainwindow.cpp
> +    for(qsizetype i = 0; i < settings->childKeys().size(); i++) {
После auto может не указатель а ссылка
Надо глянуть что childKeys возвращает

2021-09-17 18:10 UTC, merged